import LightsView from './ui/LightsView';
import GroupsView from './ui/GroupsView';
import SchedulesView from './ui/SchedulesView';
import ScenesView from './ui/ScenesView';
import SensorsView from './ui/SensorsView';
import RulesView from './ui/RulesView';
import ConfigurationView from './ui/ConfigurationView';
import ResourceLinksView from './ui/ResourceLinksView';
import CapabilitiesView from './ui/CapabilitiesView';
import ConsoleView from './ui/ConsoleView';
import SettingsView from './ui/SettingsView';
import HueBridgeSelector from './ui/HueBridgeSelector';
import ActiveBridge from './api/ActiveBridge';
import React, { Co